# Required settings
# -----------------
token = 
mainServerId = 503190685118103574
inboxServerId = 503190685118103574
logChannelId = 707567899866300449

# Common settings
# ----------------------------------
prefix = c?
inboxServerPermission = manageMessages
status = Scrivimi per aiuto!
responseMessage = Ciao! Abbiamo ricevuto correttamente la tua richiesta di contatto con lo staff. Ti informo che al più presto l'amministrazione del server ti risponderà. Buona permanenza!

# Add new options below this line:
# ----------------------------------
categoryAutomation.newThread = 708745820694118432
statusType = listening
CloseMessage= Il supporto è finito e il tuo ticket è stato chiuso dallo staff.
fallbackRoleName= Supporto
